### ISSUE TITLE
Using ✓ causes compatibility issues with older browsers

### ISSUE THREAD

**Issue by pixelmachine** [sjelfull/craft-countryredirect#19]
Whilst modern browsers, will decode ✓ as UTF-8 and transmit the URL-escaped version older ones will transmit the URL as-is. Our reverse proxy (HAProxy) rejects this request by default because ✓ is outside of the HTTP specifications.

Enabling the accept-invalid-http-request HAProxy option is enough to restore availability to Internet Explorer users, but I consider this a workaround.

Possible solutions:
- Replace instances of `'✓'` with `'%E2%9C%93'` in the plugin.
- Expose the `✓` param value in settings so it can be overridden. 

On a separate note do you have any idea of when you're looking at releasing 2.1? We're looking forward to removing our workaround for the database location issue ( #12 ).

**Comment by sjelfull** [comment]
Thanks for reporting this, i'll consider both solutions in the upcoming release.

**Comment by zizther** [comment]
I have experienced a scenerio where I need to have a hash at the end of a URL, when the site loads with the hash, the ✓ causes it to not work correctly.

It would be great to have the ✓ exposed as a param value in settings so that it can be changed to a string.

For my use-case this would be quite an urgent request, I know this issue has also been open for a while too

**Comment by pixelmachine** [comment]
@zizther I suggest using [GeoMate](https://github.com/vaersaagod/geomate) instead, it's far better.

**Comment by zizther** [comment]
Thanks @pixelmachine Used that instead and worked great.

**Comment by sjelfull** [comment]
This is now fixed by adding the `queryParamsValue` config option that allows you to override this.
